{% set name = "ctapipe" %}
{% set version = "0.25.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c25825d0f01555bb36ed5829f2a50d8be1b99db492476250fcafd00effb64c5e"

build:
  number: 0
  noarch: python

outputs:
  # first package, base, only required dependencies
  - name: ctapipe-base
    build:
      script: ${PYTHON} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
      noarch: python

    entry_points:
      - 'ctapipe-info = ctapipe.tools.info:main'
      - 'ctapipe-dump-instrument = ctapipe.tools.dump_instrument:main'
      - 'ctapipe-display-dl1 = ctapipe.tools.display_dl1:main'
      - 'ctapipe-process = ctapipe.tools.process:main'
      - 'ctapipe-merge = ctapipe.tools.merge:main'
      - 'ctapipe-fileinfo = ctapipe.tools.fileinfo:main'
      - 'ctapipe-quickstart = ctapipe.tools.quickstart:main'
      - 'ctapipe-train-energy-regressor = ctapipe.tools.train_energy_regressor:main'
      - 'ctapipe-train-particle-classifier = ctapipe.tools.train_particle_classifier:main'
      - 'ctapipe-train-disp-reconstructor = ctapipe.tools.train_disp_reconstructor:main'
      - 'ctapipe-apply-models = ctapipe.tools.apply_models:main'
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=64
        - setuptools_scm >=8.0
      run:
        - python >={{ python_min }}
        - astropy-base >=5.3,<8.0a0
        - docutils
        - joblib
        - numba >=0.57
        - numpy >=1.24,<3.0.0a0
        - packaging
        - psutil
        - pytables >=3.4,<4.0.0a0
        - pyyaml >=5.1
        - requests
        - 'scikit-learn !=1.4.0'
        - scipy >=1.10,<2.0.0a0
        - tqdm >=4.32
        - traitlets >=5.6,<6

    test:
      imports:
        - ctapipe
        - ctapipe.core
        - ctapipe.image
        - ctapipe.calib
        - ctapipe.instrument
        - ctapipe.visualization
        - ctapipe.io
      commands:
        - ctapipe-info --version
        - pip check
        # make sure we have a version
        - pip freeze | grep ctapipe | grep -v ctapipe==0.0.0
      requires:
        - python {{ python_min }}
        - pip

  # second package, a meta package pinning ctapipe-base and including all optional dependencies
  - name: ctapipe
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('ctapipe-base', max_pin='x.x.x') }}
        - bokeh >=3.0,<4.0.0a0
        - eventio >=1.9.1,<2.0.0a0
        - iminuit >=2.0,<3
        - matplotlib-base >=3.0,<4.0.0a0
        - pyirf >=0.12.0,<0.13.0a0
    test:
      imports:
        - ctapipe.visualization.bokeh

about:
  home: https://github.com/cta-observatory/ctapipe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Low-level data processing pipeline software for the CTAO (the Cherenkov Telescope Array Observatory)

  description: |
    Low-level data processing pipeline software for the CTAO (the Cherenkov Telescope Array Observatory)
  doc_url: https://ctapipe.readthedocs.io/
  dev_url: https://github.com/cta-observatory/ctapipe

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
