{% set name = "ctapipe" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 728be900f61e95977b2346137f7b0bebf9e83cb1f9895a18cf6ea88f57a11b77

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - ctapipe-info = ctapipe.tools.info:main
    - ctapipe-camdemo = ctapipe.tools.camdemo:main
    - ctapipe-dump-triggers = ctapipe.tools.dump_triggers:main
    - ctapipe-chargeres-extract = ctapipe.tools.extract_charge_resolution:main
    - ctapipe-chargeres-plot = ctapipe.tools.plot_charge_resolution:main
    - ctapipe-dump-instrument=ctapipe.tools.dump_instrument:main
    - ctapipe-event-viewer = ctapipe.tools.bokeh.file_viewer:main
    - ctapipe-display-tel-events = ctapipe.tools.display_events_single_tel:main
    - ctapipe-display-imagesums = ctapipe.tools.display_summed_images:main
    - ctapipe-reconstruct-muons = ctapipe.tools.muon_reconstruction:main
    - ctapipe-display-integration = ctapipe.tools.display_integrator:main
    - ctapipe-display-dl1 = ctapipe.tools.display_dl1:main
    - ctapipe-stage1-process = ctapipe.tools.stage1:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - astropy >=4,<5
    - bokeh >=1.0,<2.0.0a0
    - eventio >=1.5.1,<2.0.0a0
    - iminuit >=2.0,<3
    - joblib
    - matplotlib-base >=3.0,<4.0.0a0
    - numba >=0.43
    - numpy >=1.17
    - psutil
    - scikit-learn
    - scipy >=1.2
    - pytables >=3.4
    - tqdm >=4.32
    - traitlets >=5.1,<6
    - zstandard
    - requests
    - setuptools_scm >=3.4
    - h5py
    - importlib_resources

test:
  imports:
    - ctapipe
    - ctapipe.core
    - ctapipe.image
    - ctapipe.calib
    - ctapipe.instrument
    - ctapipe.visualization
    - ctapipe.io
  commands:
    - ctapipe-info --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctapipe
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Low-level data processing pipeline software for CTA (the Cherenkov Telescope Array)

  description: |
    Low-level data processing pipeline software for CTA (the Cherenkov Telescope Array)
  doc_url: https://cta-observatory.github.io/ctapipe/
  dev_url: https://github.com/cta-observatory/ctapipe

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
